### ISSUE TITLE
Error: Cannot find module '/mnt/data/eosio-graphql/service.js'

### ISSUE THREAD

**Issue by cppfuns** [EOS-Nation/eosio-graphql#5]
root@iZj6cefkuu3496i13for2dZ:/mnt/data/eosio-graphql# npm start

> eosio-graphql@0.2.0 start /mnt/data/eosio-graphql
> tsc && node service.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/mnt/data/eosio-graphql/service.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eosio-graphql@0.2.0 start: `tsc && node service.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eosio-graphql@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-27T12_44_18_112Z-debug.log

**Comment by cppfuns** [comment]
@DenisCarriere Can you help me see this question?

**Comment by cppfuns** [comment]
tsconfig.json 

"lib": [
  "es2017",
  "dom",
  "esnext"
]
